---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: echoer
spec:
  description: First cluster task from the Tekton Tutorial
  steps:
    - image: alpine
      name: what-says-the-cat
      script: |
        #!/bin/sh
        echo 'Meeow!! from Tekton 😺🚀'

        echo -e "\n\nMounted filesystems ..."
        df -h
        echo -e "\n\nThe root filesystem / ..."
        ls -altr /
        echo -e "\n\nThe workspace directory /workspace/* ..."
        cd /workspace
        find .
        echo -e "\n\nThe tekton directory /tekton/* ..."
        cd /tekton
        find .

        echo -e "\n\nUser information ..."
        echo "id = $(id)"
        echo "id -ru = $(id -ru)"
        echo "id -rg = $(id -rg)"
        echo "id -rG = $(id -rG)"
        echo "id -un = $(id -un)"
        echo "id -gn = $(id -gn)"
        echo "id -Gn = $(id -Gn)"
