apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
spec:
  description: Read and display README file.
  workspaces:
  - name: source
  steps:
  - name: read
    image: quay.io/openshift/origin-cli:4.12
    script: | 
      #!/usr/bin/env sh
      cat $(workspaces.source.path)/README.md