apiVersion: v1
imagePullSecrets:
- name: epyc
kind: ServiceAccount
metadata:
  name: epyc-sa
  namespace: tektontutorial
secrets:
- name: epyc
---
apiVersion: v1
kind: Service
metadata:
  name: demo-greeter
spec:
  selector:
    app: demo-greeter
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-greeter
spec:
  selector:
    matchLabels:
      app: demo-greeter
  template:
    metadata:
      labels:
        app: demo-greeter
    spec:
      containers:
      - name: demo-greeter
        image: epyc.2i.at:18444/tektontutorial/tekton-tutorial-greeter:latest
        ports:
        - containerPort: 8080
        ServiceAccount: epyc-sa
        ServiceAccountName: epyc-sa
